DROP TABLE IF EXISTS users;
CREATE TABLE users {id SERIAL PRIMARY KEY, firstName VARCHAR(20), lastName VARCHAR(20), age INTEGER, email VARCHAR(200), email VARCHAR(200), img VARCHAR(200), hash VARCHAR(2000)};

SELECT * FROM users;